import * as Joi from 'joi';

export const configValidationSchema = Joi.object({
	NODE_ENV: Joi.string().valid('dev', 'integ', 'test', 'prod').default('dev'),
	PORT: Joi.number().default(3000),
	DATABASE_USER: Joi.string().required(),
	DATABASE_PASSWORD: Joi.string().required(),
	DATABASE_HOST: Joi.string().required(),
	DATABASE_PORT: Joi.number().required(),
	DATABASE_DB: Joi.string().required(),
	KAKAO_CLIENT_ID: Joi.string().required(),
	KAKAO_CALLBACK_URL: Joi.string().required(),
	FACEBOOK_CLIENT_ID: Joi.string().required(),
	FACEBOOK_SECRET_KEY: Joi.string().required(),
	FACEBOOK_CALLBACK_URL: Joi.string().required(),
	JWT_ACCESS_TOKEN_SECRET: Joi.string().required(),
	JWT_ACCESS_TOKEN_EXPIRATION_TIME: Joi.string().required(),
	JWT_ACCESS_TOKEN_EXPIRATION_TIME_ADMIN: Joi.string().required(),
	JWT_REFRESH_TOKEN_SECRET: Joi.string().required(),
	JWT_REFRESH_TOKEN_EXPIRATION_TIME: Joi.string().required(),
	EMAIL: Joi.string().required(),
	EMAIL_PASSWORD: Joi.string().required(),
	NCLOUD_ACCESS_KEY_ID: Joi.string().required(),
	NCLOUD_SECRET_ACCESS_KEY: Joi.string().required(),
	NCLOUD_STORAGE_ENDPOINT: Joi.string().required(),
	NCLOUD_STORAGE_BUCKET: Joi.string().required(),
	SSH_HOST: Joi.string().required(),
	SSH_USERNAME: Joi.string().required(),
	SSH_PORT: Joi.string().required(),
	SSH_PASSWORD: Joi.string().required(),
});
